/*
 * Copyright (c) 2000-2005 Regents of the University of California.
 * All rights reserved.
 *
 * This software was developed at the University of California, Irvine.
 *
 * Redistribution and use in source and binary forms are permitted
 * provided that the above copyright notice and this paragraph are
 * duplicated in all such forms and that any documentation,
 * advertising materials, and other materials related to such
 * distribution and use acknowledge that the software was developed
 * by the University of California, Irvine.  The name of the
 * University may not be used to endorse or promote products derived
 * from this software without specific prior written permission.
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
 * WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */
package edu.uci.isr.xarch.javaimplementation;

import java.util.Collection;
import edu.uci.isr.xarch.XArchActionMetadata;
import edu.uci.isr.xarch.XArchTypeMetadata;
import edu.uci.isr.xarch.XArchPropertyMetadata;

/**
 * Interface for accessing objects of the
 * JavaClassFile <code>xsi:type</code> in the
 * javaimplementation namespace.
 * 
 * @author Automatically generated by xArch apigen
 */
public interface IJavaClassFile extends edu.uci.isr.xarch.IXArchElement{

	public final static XArchTypeMetadata TYPE_METADATA = new XArchTypeMetadata(
		XArchTypeMetadata.XARCH_ELEMENT,
		"javaimplementation", "JavaClassFile", edu.uci.isr.xarch.IXArchElement.TYPE_METADATA,
		new XArchPropertyMetadata[]{
			XArchPropertyMetadata.createElement("javaClassName", "javaimplementation", "JavaClassName", 1, 1),
			XArchPropertyMetadata.createElement("url", "instance", "XMLLink", 0, 1)},
		new XArchActionMetadata[]{});

	/**
	 * Set the javaClassName for this JavaClassFile.
	 * @param value new javaClassName
	 */
	public void setJavaClassName(IJavaClassName value);

	/**
	 * Clear the javaClassName from this JavaClassFile.
	 */
	public void clearJavaClassName();

	/**
	 * Get the javaClassName from this JavaClassFile.
	 * @return javaClassName
	 */
	public IJavaClassName getJavaClassName();

	/**
	 * Determine if this JavaClassFile has the given javaClassName
	 * @param javaClassNameToCheck javaClassName to compare
	 * @return <code>true</code> if the javaClassNames are equivalent,
	 * <code>false</code> otherwise
	 */
	public boolean hasJavaClassName(IJavaClassName javaClassNameToCheck);

	/**
	 * Set the url for this JavaClassFile.
	 * @param value new url
	 */
	public void setUrl(edu.uci.isr.xarch.instance.IXMLLink value);

	/**
	 * Clear the url from this JavaClassFile.
	 */
	public void clearUrl();

	/**
	 * Get the url from this JavaClassFile.
	 * @return url
	 */
	public edu.uci.isr.xarch.instance.IXMLLink getUrl();

	/**
	 * Determine if this JavaClassFile has the given url
	 * @param urlToCheck url to compare
	 * @return <code>true</code> if the urls are equivalent,
	 * <code>false</code> otherwise
	 */
	public boolean hasUrl(edu.uci.isr.xarch.instance.IXMLLink urlToCheck);
	/**
	 * Determine if another JavaClassFile is equivalent to this one, ignoring
	 * ID's.
	 * @param JavaClassFileToCheck JavaClassFile to compare to this one.
	 * @return <code>true</code> if all the child elements of this
	 * JavaClassFile are equivalent, <code>false</code> otherwise.
	 */
	public boolean isEquivalent(IJavaClassFile JavaClassFileToCheck);

}
