/*
 * Copyright (c) 2000-2005 Regents of the University of California.
 * All rights reserved.
 *
 * This software was developed at the University of California, Irvine.
 *
 * Redistribution and use in source and binary forms are permitted
 * provided that the above copyright notice and this paragraph are
 * duplicated in all such forms and that any documentation,
 * advertising materials, and other materials related to such
 * distribution and use acknowledge that the software was developed
 * by the University of California, Irvine.  The name of the
 * University may not be used to endorse or promote products derived
 * from this software without specific prior written permission.
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
 * WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */
package edu.uci.isr.xarch.versions;

import java.util.Collection;
import edu.uci.isr.xarch.XArchActionMetadata;
import edu.uci.isr.xarch.XArchTypeMetadata;
import edu.uci.isr.xarch.XArchPropertyMetadata;

/**
 * Interface for accessing objects of the
 * ComponentTypeVersionGraph <code>xsi:type</code> in the
 * versions namespace.
 * 
 * @author Automatically generated by xArch apigen
 */
public interface IComponentTypeVersionGraph extends edu.uci.isr.xarch.IXArchElement{

	public final static XArchTypeMetadata TYPE_METADATA = new XArchTypeMetadata(
		XArchTypeMetadata.XARCH_ELEMENT,
		"versions", "ComponentTypeVersionGraph", edu.uci.isr.xarch.IXArchElement.TYPE_METADATA,
		new XArchPropertyMetadata[]{
			XArchPropertyMetadata.createAttribute("id", "instance", "Identifier", null, null),
			XArchPropertyMetadata.createElement("description", "instance", "Description", 1, 1),
			XArchPropertyMetadata.createElement("node", "versions", "Node", 0, XArchPropertyMetadata.UNBOUNDED)},
		new XArchActionMetadata[]{});

	/**
	 * Set the id attribute on this ComponentTypeVersionGraph.
	 * @param id id
	 * @exception FixedValueException if the attribute has a fixed value
	 * and the value passed is not the fixed value.
	*/
	public void setId(String id);

	/**
	 * Remove the id attribute from this ComponentTypeVersionGraph.
	 */
	public void clearId();

	/**
	 * Get the id attribute from this ComponentTypeVersionGraph.
	 * if the attribute has a fixed value, this function will
	 * return that fixed value, even if it is not actually present
	 * in the XML document.
	 * @return id on this ComponentTypeVersionGraph
	 */
	public String getId();

	/**
	 * Determine if the id attribute on this ComponentTypeVersionGraph
	 * has the given value.
	 * @param id Attribute value to compare
	 * @return <code>true</code> if they match; <code>false</code>
	 * otherwise.
	 */
	public boolean hasId(String id);


	/**
	 * Set the description for this ComponentTypeVersionGraph.
	 * @param value new description
	 */
	public void setDescription(edu.uci.isr.xarch.instance.IDescription value);

	/**
	 * Clear the description from this ComponentTypeVersionGraph.
	 */
	public void clearDescription();

	/**
	 * Get the description from this ComponentTypeVersionGraph.
	 * @return description
	 */
	public edu.uci.isr.xarch.instance.IDescription getDescription();

	/**
	 * Determine if this ComponentTypeVersionGraph has the given description
	 * @param descriptionToCheck description to compare
	 * @return <code>true</code> if the descriptions are equivalent,
	 * <code>false</code> otherwise
	 */
	public boolean hasDescription(edu.uci.isr.xarch.instance.IDescription descriptionToCheck);

	/**
	 * Add a node to this ComponentTypeVersionGraph.
	 * @param newNode node to add.
	 */
	public void addNode(INode newNode);

	/**
	 * Add a collection of nodes to this ComponentTypeVersionGraph.
	 * @param nodes nodes to add.
	 */
	public void addNodes(Collection nodes);

	/**
	 * Remove all nodes from this ComponentTypeVersionGraph.
	 */
	public void clearNodes();

	/**
	 * Remove the given node from this ComponentTypeVersionGraph.
	 * Matching is done by the <code>isEquivalent(...)</code> function.
	 * @param nodeToRemove node to remove.
	 */
	public void removeNode(INode nodeToRemove);

	/**
	 * Remove all the given nodes from this ComponentTypeVersionGraph.
	 * Matching is done by the <code>isEquivalent(...)</code> function.
	 * @param nodes node to remove.
	 */
	public void removeNodes(Collection nodes);

	/**
	 * Get all the nodes from this ComponentTypeVersionGraph.
	 * @return all nodes in this ComponentTypeVersionGraph.
	 */
	public Collection getAllNodes();

	/**
	 * Determine if this ComponentTypeVersionGraph contains a given node.
	 * @return <code>true</code> if this ComponentTypeVersionGraph contains the given
	 * nodeToCheck, <code>false</code> otherwise.
	 */
	public boolean hasNode(INode nodeToCheck);

	/**
	 * Determine if this ComponentTypeVersionGraph contains the given set of nodes.
	 * @param nodesToCheck nodes to check for.
	 * @return Collection of <code>java.lang.Boolean</code>.  If the i<sup>th</sup>
	 * element in <code>nodes</code> was found, then the i<sup>th</sup>
	 * element of the collection will be set to <code>true</code>, otherwise it
	 * will be set to <code>false</code>.  Matching is done with the
	 * <code>isEquivalent(...)</code> method.
	 */
	public Collection hasNodes(Collection nodesToCheck);

	/**
	 * Determine if this ComponentTypeVersionGraph contains each element in the 
	 * given set of nodes.
	 * @param nodesToCheck nodes to check for.
	 * @return <code>true</code> if every element in
	 * <code>nodes</code> is found in this ComponentTypeVersionGraph,
	 * <code>false</code> otherwise.
	 */
	public boolean hasAllNodes(Collection nodesToCheck);

	/**
	 * Gets the node from this ComponentTypeVersionGraph with the given
	 * id.
	 * @param id ID to look for.
	 * @return node with the given ID, or <code>null</code> if not found.
	 */
	public INode getNode(String id);

	/**
	 * Gets the nodes from this ComponentTypeVersionGraph with the given
	 * ids.
	 * @param ids ID to look for.
	 * @return nodes with the given IDs.  If an element with a given
	 * ID was not found, that ID is ignored.
	 */
	public Collection getNodes(Collection ids);

	/**
	 * Determine if another ComponentTypeVersionGraph has the same
	 * id as this one.
	 * @param ComponentTypeVersionGraphToCheck ComponentTypeVersionGraph to compare with this
	 * one.
	 */
	public boolean isEqual(IComponentTypeVersionGraph ComponentTypeVersionGraphToCheck);
	/**
	 * Determine if another ComponentTypeVersionGraph is equivalent to this one, ignoring
	 * ID's.
	 * @param ComponentTypeVersionGraphToCheck ComponentTypeVersionGraph to compare to this one.
	 * @return <code>true</code> if all the child elements of this
	 * ComponentTypeVersionGraph are equivalent, <code>false</code> otherwise.
	 */
	public boolean isEquivalent(IComponentTypeVersionGraph ComponentTypeVersionGraphToCheck);

}
