/*
 * Copyright (c) 2000-2005 Regents of the University of California.
 * All rights reserved.
 *
 * This software was developed at the University of California, Irvine.
 *
 * Redistribution and use in source and binary forms are permitted
 * provided that the above copyright notice and this paragraph are
 * duplicated in all such forms and that any documentation,
 * advertising materials, and other materials related to such
 * distribution and use acknowledge that the software was developed
 * by the University of California, Irvine.  The name of the
 * University may not be used to endorse or promote products derived
 * from this software without specific prior written permission.
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
 * WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */
package edu.uci.isr.xarch.pladiff;

import java.util.Collection;
import edu.uci.isr.xarch.XArchActionMetadata;
import edu.uci.isr.xarch.XArchTypeMetadata;
import edu.uci.isr.xarch.XArchPropertyMetadata;

/**
 * Interface for accessing objects of the
 * DiffLocation <code>xsi:type</code> in the
 * pladiff namespace.
 * 
 * @author Automatically generated by xArch apigen
 */
public interface IDiffLocation extends edu.uci.isr.xarch.IXArchElement{

	public final static XArchTypeMetadata TYPE_METADATA = new XArchTypeMetadata(
		XArchTypeMetadata.XARCH_ELEMENT,
		"pladiff", "DiffLocation", edu.uci.isr.xarch.IXArchElement.TYPE_METADATA,
		new XArchPropertyMetadata[]{
			XArchPropertyMetadata.createElement("location", "instance", "Description", 1, 1)},
		new XArchActionMetadata[]{});

	/**
	 * Set the location for this DiffLocation.
	 * @param value new location
	 */
	public void setLocation(edu.uci.isr.xarch.instance.IDescription value);

	/**
	 * Clear the location from this DiffLocation.
	 */
	public void clearLocation();

	/**
	 * Get the location from this DiffLocation.
	 * @return location
	 */
	public edu.uci.isr.xarch.instance.IDescription getLocation();

	/**
	 * Determine if this DiffLocation has the given location
	 * @param locationToCheck location to compare
	 * @return <code>true</code> if the locations are equivalent,
	 * <code>false</code> otherwise
	 */
	public boolean hasLocation(edu.uci.isr.xarch.instance.IDescription locationToCheck);
	/**
	 * Determine if another DiffLocation is equivalent to this one, ignoring
	 * ID's.
	 * @param DiffLocationToCheck DiffLocation to compare to this one.
	 * @return <code>true</code> if all the child elements of this
	 * DiffLocation are equivalent, <code>false</code> otherwise.
	 */
	public boolean isEquivalent(IDiffLocation DiffLocationToCheck);

}
