/*
 * Copyright (c) 2000-2005 Regents of the University of California.
 * All rights reserved.
 *
 * This software was developed at the University of California, Irvine.
 *
 * Redistribution and use in source and binary forms are permitted
 * provided that the above copyright notice and this paragraph are
 * duplicated in all such forms and that any documentation,
 * advertising materials, and other materials related to such
 * distribution and use acknowledge that the software was developed
 * by the University of California, Irvine.  The name of the
 * University may not be used to endorse or promote products derived
 * from this software without specific prior written permission.
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
 * WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */
package edu.uci.isr.xarch.lookupimplementation;

import java.util.*;

import edu.uci.isr.xarch.*;

import org.w3c.dom.*;

import edu.uci.isr.xarch.IXArch;
import edu.uci.isr.xarch.IXArchContext;

/**
 * The context interface for the lookupimplementation package.
 * This interface is used to create objects that are used
 * in the lookupimplementation namespace.
 *
 * @author Automatically Generated by xArch apigen
 */
public interface ILookupimplementationContext extends IXArchContext{

	/**
	 * Create an ILookupImplementation object in this namespace.
	 * @return New ILookupImplementation object.
	 */
	public ILookupImplementation createLookupImplementation();

	/**
	 * Brings an ILookupImplementation object created in another
	 * context into this context.
	 * @param value Object to recontextualize.
	 * @return <code>value</code> object in this namespace.
	 */
	public ILookupImplementation recontextualizeLookupImplementation(ILookupImplementation value);

	/**
	 * Promote an object of type <code>edu.uci.isr.xarch.implementation.IImplementation</code>
	 * to one of type <code>ILookupImplementation</code>.  xArch APIs
	 * are structured in such a way that a regular cast is not possible
	 * to change interface types, so casting must be done through these
	 * promotion functions.  If the <code>edu.uci.isr.xarch.implementation.IImplementation</code>
	 * object wraps a DOM element that is the base type, then the 
	 * <code>xsi:type</code> of the base element is promoted.  Otherwise, 
	 * it is left unchanged.
	 *
	 * This function also emits an <CODE>XArchEvent</CODE> with type
	 * PROMOTE_TYPE.  The source for this events is the pre-promoted
	 * IXArchElement object (should no longer be used), and the
	 * target is the post-promotion object.  The target name is
	 * the name of the interface class that was the target of the
	 * promotion.
	 * 
	 * @param value Object to promote.
	 * @return Promoted object.
	 */
	public ILookupImplementation promoteToLookupImplementation(
	edu.uci.isr.xarch.implementation.IImplementation value);

	/**
	 * Create an ILookupName object in this namespace.
	 * @return New ILookupName object.
	 */
	public ILookupName createLookupName();

	/**
	 * Brings an ILookupName object created in another
	 * context into this context.
	 * @param value Object to recontextualize.
	 * @return <code>value</code> object in this namespace.
	 */
	public ILookupName recontextualizeLookupName(ILookupName value);


	public final static XArchTypeMetadata TYPE_METADATA = new XArchTypeMetadata(
		XArchTypeMetadata.XARCH_CONTEXT,
		"lookupimplementation", null, null,
		new XArchPropertyMetadata[]{},
		new XArchActionMetadata[]{
			new XArchActionMetadata(XArchActionMetadata.CREATE, null, ILookupImplementation.TYPE_METADATA),
			new XArchActionMetadata(XArchActionMetadata.RECONTEXTUALIZE, ILookupImplementation.TYPE_METADATA, ILookupImplementation.TYPE_METADATA),
			new XArchActionMetadata(XArchActionMetadata.PROMOTE, edu.uci.isr.xarch.implementation.IImplementation.TYPE_METADATA, ILookupImplementation.TYPE_METADATA),
			new XArchActionMetadata(XArchActionMetadata.CREATE, null, ILookupName.TYPE_METADATA),
			new XArchActionMetadata(XArchActionMetadata.RECONTEXTUALIZE, ILookupName.TYPE_METADATA, ILookupName.TYPE_METADATA)});

}

