/*
 * Copyright (c) 2000-2005 Regents of the University of California.
 * All rights reserved.
 *
 * This software was developed at the University of California, Irvine.
 *
 * Redistribution and use in source and binary forms are permitted
 * provided that the above copyright notice and this paragraph are
 * duplicated in all such forms and that any documentation,
 * advertising materials, and other materials related to such
 * distribution and use acknowledge that the software was developed
 * by the University of California, Irvine.  The name of the
 * University may not be used to endorse or promote products derived
 * from this software without specific prior written permission.
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
 * WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */
package edu.uci.isr.xarch.types;

import org.w3c.dom.*;

import edu.uci.isr.xarch.*;

import java.util.*;

/**
 * DOM-Based implementation of the ISubArchitecture interface.
 *
 * @author Automatically generated by xArch apigen.
 */
public class SubArchitectureImpl implements ISubArchitecture, DOMBased{
	
	public static final String XSD_TYPE_NSURI = TypesConstants.NS_URI;
	public static final String XSD_TYPE_NAME = "SubArchitecture";
	
	protected IXArch xArch;
	
	/** Tag name for archStructures in this object. */
	public static final String ARCH_STRUCTURE_ELT_NAME = "archStructure";
	/** Tag name for signatureInterfaceMappings in this object. */
	public static final String SIGNATURE_INTERFACE_MAPPING_ELT_NAME = "signatureInterfaceMapping";

	
	protected Element elt;
	
	private static SequenceOrder seqOrd = new SequenceOrder(
		new QName[]{
			new QName(TypesConstants.NS_URI, ARCH_STRUCTURE_ELT_NAME),
			new QName(TypesConstants.NS_URI, SIGNATURE_INTERFACE_MAPPING_ELT_NAME)
		}
	);
	
	public SubArchitectureImpl(Element elt){
		if(elt == null){
			throw new IllegalArgumentException("Element cannot be null.");
		}
		this.elt = elt;
	}

	public Node getDOMNode(){
		return elt;
	}
	
	public void setDOMNode(Node node){
		if(node.getNodeType() != Node.ELEMENT_NODE){
			throw new IllegalArgumentException("Base DOM node of this type must be an Element.");
		}
		elt = (Element)node;
	}
	
	protected static SequenceOrder getSequenceOrder(){
		return seqOrd;
	}
	
	public void setXArch(IXArch xArch){
		this.xArch = xArch;
	}
	
	public IXArch getXArch(){
		return this.xArch;
	}

	public IXArchElement cloneElement(int depth){
		synchronized(DOMUtils.getDOMLock(elt)){
			Document doc = elt.getOwnerDocument();
			if(depth == 0){
				Element cloneElt = (Element)elt.cloneNode(false);
				cloneElt = (Element)doc.importNode(cloneElt, true);
				SubArchitectureImpl cloneImpl = new SubArchitectureImpl(cloneElt);
				cloneImpl.setXArch(getXArch());
				return cloneImpl;
			}
			else if(depth == 1){
				Element cloneElt = (Element)elt.cloneNode(false);
				cloneElt = (Element)doc.importNode(cloneElt, true);
				SubArchitectureImpl cloneImpl = new SubArchitectureImpl(cloneElt);
				cloneImpl.setXArch(getXArch());
				
				NodeList nl = elt.getChildNodes();
				int size = nl.getLength();
				for(int i = 0; i < size; i++){
					Node n = nl.item(i);
					Node cloneNode = (Node)n.cloneNode(false);
					cloneNode = doc.importNode(cloneNode, true);
					cloneElt.appendChild(cloneNode);
				}
				return cloneImpl;
			}
			else /* depth = infinity */{
				Element cloneElt = (Element)elt.cloneNode(true);
				cloneElt = (Element)doc.importNode(cloneElt, true);
				SubArchitectureImpl cloneImpl = new SubArchitectureImpl(cloneElt);
				cloneImpl.setXArch(getXArch());
				return cloneImpl;
			}
		}
	}

	//Override 'equals' to be DOM-based...	
	public boolean equals(Object o){
		if(o == null){
			return false;
		}
		if(!(o instanceof DOMBased)){
			return super.equals(o);
		}
		DOMBased db = (DOMBased)o;
		Node dbNode = db.getDOMNode();
		return dbNode.equals(getDOMNode());
	}

	//Override 'hashCode' to be based on the underlying node
	public int hashCode(){
		return getDOMNode().hashCode();
	}

	/**
	 * For internal use only.
	 */
	private static Object makeDerivedWrapper(Element elt, String baseTypeName){
		synchronized(DOMUtils.getDOMLock(elt)){
			QName typeName = XArchUtils.getXSIType(elt);
			if(typeName == null){
				return null;
			}
			else{
				if(!DOMUtils.hasXSIType(elt, "http://www.ics.uci.edu/pub/arch/xArch/types.xsd", baseTypeName)){
					try{
						String packageTitle = XArchUtils.getPackageTitle(typeName.getNamespaceURI());
						String packageName = XArchUtils.getPackageName(packageTitle);
						String implName = XArchUtils.getImplName(packageName, typeName.getName());
						Class c = Class.forName(implName);
						java.lang.reflect.Constructor con = c.getConstructor(new Class[]{Element.class});
						Object o = con.newInstance(new Object[]{elt});
						return o;
					}
					catch(Exception e){
						//Lots of bad things could happen, but this
						//is OK, because this is best-effort anyway.
					}
				}
				return null;
			}
		}
	}

	public XArchTypeMetadata getTypeMetadata(){
		return ISubArchitecture.TYPE_METADATA;
	}

	public XArchInstanceMetadata getInstanceMetadata(){
		return new XArchInstanceMetadata(XArchUtils.getPackageTitle(elt.getNamespaceURI()));
	}

	public void setArchStructure(edu.uci.isr.xarch.instance.IXMLLink value){
		if(!(value instanceof DOMBased)){
			throw new IllegalArgumentException("Cannot handle non-DOM-based xArch entities.");
		}
		{
			edu.uci.isr.xarch.instance.IXMLLink oldElt = getArchStructure();
			DOMUtils.removeChildren(elt, TypesConstants.NS_URI, ARCH_STRUCTURE_ELT_NAME);
			
			IXArch context = getXArch();
			if(context != null){
				context.fireXArchEvent(
					new XArchEvent(this, 
					XArchEvent.CLEAR_EVENT,
					XArchEvent.ELEMENT_CHANGED,
					"archStructure", oldElt,
					XArchUtils.getDefaultXArchImplementation().isContainedIn(xArch, this), true)
				);
			}
		}
		Element newChildElt = (Element)(((DOMBased)value).getDOMNode());
		newChildElt = DOMUtils.cloneAndRename(newChildElt, TypesConstants.NS_URI, ARCH_STRUCTURE_ELT_NAME);
		((DOMBased)value).setDOMNode(newChildElt);
		
		synchronized(DOMUtils.getDOMLock(elt)){
			elt.appendChild(newChildElt);
			DOMUtils.order(elt, getSequenceOrder());
		}
		
		IXArch context = getXArch();
		if(context != null){
			context.fireXArchEvent(
				new XArchEvent(this, 
				XArchEvent.SET_EVENT,
				XArchEvent.ELEMENT_CHANGED,
				"archStructure", value,
				XArchUtils.getDefaultXArchImplementation().isContainedIn(xArch, this))
			);
		}
	}
	
	public void clearArchStructure(){
		edu.uci.isr.xarch.instance.IXMLLink oldElt = getArchStructure();
		DOMUtils.removeChildren(elt, TypesConstants.NS_URI, ARCH_STRUCTURE_ELT_NAME);
		
		IXArch context = getXArch();
		if(context != null){
			context.fireXArchEvent(
				new XArchEvent(this, 
				XArchEvent.CLEAR_EVENT,
				XArchEvent.ELEMENT_CHANGED,
				"archStructure", oldElt,
				XArchUtils.getDefaultXArchImplementation().isContainedIn(xArch, this))
			);
		}
	}
	
	public edu.uci.isr.xarch.instance.IXMLLink getArchStructure(){
		NodeList nl = DOMUtils.getChildren(elt, TypesConstants.NS_URI, ARCH_STRUCTURE_ELT_NAME);
		if(nl.getLength() == 0){
			return null;
		}
		else{
			Element el = (Element)nl.item(0);
			IXArch de = getXArch();
			if(de != null){
				IXArchElement cachedXArchElt = de.getWrapper(el);
				if(cachedXArchElt != null){
					return (edu.uci.isr.xarch.instance.IXMLLink)cachedXArchElt;
				}
			}
			
			Object o = makeDerivedWrapper(el, "XMLLink");
			if(o != null){
				try{
					((edu.uci.isr.xarch.IXArchElement)o).setXArch(getXArch());
					if(de != null){
						de.cacheWrapper(el, ((edu.uci.isr.xarch.IXArchElement)o));
					}
					return (edu.uci.isr.xarch.instance.IXMLLink)o;
				}
				catch(Exception e){}
			}
			edu.uci.isr.xarch.instance.XMLLinkImpl eltImpl = new edu.uci.isr.xarch.instance.XMLLinkImpl(el);
			eltImpl.setXArch(getXArch());
			if(de != null){
				de.cacheWrapper(el, ((edu.uci.isr.xarch.IXArchElement)eltImpl));
			}
			return eltImpl;
		}
	}
	
	public boolean hasArchStructure(edu.uci.isr.xarch.instance.IXMLLink value){
		edu.uci.isr.xarch.instance.IXMLLink thisValue = getArchStructure();
		edu.uci.isr.xarch.instance.IXMLLink thatValue = value;
		
		if((thisValue == null) && (thatValue == null)){
			return true;
		}
		else if((thisValue == null) && (thatValue != null)){
			return false;
		}
		else if((thisValue != null) && (thatValue == null)){
			return false;
		}
		return thisValue.isEquivalent(thatValue);
	}

	public void addSignatureInterfaceMapping(ISignatureInterfaceMapping newSignatureInterfaceMapping){
		if(!(newSignatureInterfaceMapping instanceof DOMBased)){
			throw new IllegalArgumentException("Cannot handle non-DOM-based xArch entities.");
		}
		Element newChildElt = (Element)(((DOMBased)newSignatureInterfaceMapping).getDOMNode());
		newChildElt = DOMUtils.cloneAndRename(newChildElt, TypesConstants.NS_URI, SIGNATURE_INTERFACE_MAPPING_ELT_NAME);
		((DOMBased)newSignatureInterfaceMapping).setDOMNode(newChildElt);

		synchronized(DOMUtils.getDOMLock(elt)){
			elt.appendChild(newChildElt);
			DOMUtils.order(elt, getSequenceOrder());
		}

		IXArch context = getXArch();
		if(context != null){
			context.fireXArchEvent(
				new XArchEvent(this, 
				XArchEvent.ADD_EVENT,
				XArchEvent.ELEMENT_CHANGED,
				"signatureInterfaceMapping", newSignatureInterfaceMapping,
				XArchUtils.getDefaultXArchImplementation().isContainedIn(xArch, this))
			);
		}
	}
		
	public void addSignatureInterfaceMappings(Collection signatureInterfaceMappings){
		for(Iterator en = signatureInterfaceMappings.iterator(); en.hasNext(); ){
			ISignatureInterfaceMapping elt = (ISignatureInterfaceMapping)en.next();
			addSignatureInterfaceMapping(elt);
		}
	}		
		
	public void clearSignatureInterfaceMappings(){
		//DOMUtils.removeChildren(elt, TypesConstants.NS_URI, SIGNATURE_INTERFACE_MAPPING_ELT_NAME);
		Collection coll = getAllSignatureInterfaceMappings();
		removeSignatureInterfaceMappings(coll);
	}
	
	public void removeSignatureInterfaceMapping(ISignatureInterfaceMapping signatureInterfaceMappingToRemove){
		if(!(signatureInterfaceMappingToRemove instanceof DOMBased)){
			throw new IllegalArgumentException("Cannot handle non-DOM-based xArch entities.");
		}
		NodeList nl = DOMUtils.getChildren(elt, TypesConstants.NS_URI, SIGNATURE_INTERFACE_MAPPING_ELT_NAME);
		for(int i = 0; i < nl.getLength(); i++){
			Node n = nl.item(i);
			if(n == ((DOMBased)signatureInterfaceMappingToRemove).getDOMNode()){
				synchronized(DOMUtils.getDOMLock(elt)){
					elt.removeChild(n);
				}

				IXArch context = getXArch();
				if(context != null){
					context.fireXArchEvent(
						new XArchEvent(this, 
						XArchEvent.REMOVE_EVENT,
						XArchEvent.ELEMENT_CHANGED,
						"signatureInterfaceMapping", signatureInterfaceMappingToRemove,
						XArchUtils.getDefaultXArchImplementation().isContainedIn(xArch, this))
					);
				}

				return;
			}
		}
	}
	
	public void removeSignatureInterfaceMappings(Collection signatureInterfaceMappings){
		for(Iterator en = signatureInterfaceMappings.iterator(); en.hasNext(); ){
			ISignatureInterfaceMapping elt = (ISignatureInterfaceMapping)en.next();
			removeSignatureInterfaceMapping(elt);
		}
	}
	
	public Collection getAllSignatureInterfaceMappings(){
		NodeList nl = DOMUtils.getChildren(elt, TypesConstants.NS_URI, SIGNATURE_INTERFACE_MAPPING_ELT_NAME);
		int nlLength = nl.getLength();
		ArrayList v = new ArrayList(nlLength);
		IXArch de = getXArch();
		for(int i = 0; i < nlLength; i++){
			Element el = (Element)nl.item(i);
			boolean found = false;
			if(de != null){
				IXArchElement cachedXArchElt = de.getWrapper(el);
				if(cachedXArchElt != null){
					v.add((ISignatureInterfaceMapping)cachedXArchElt);
					found = true;
				}
			}
			if(!found){
				Object o = makeDerivedWrapper(el, "SignatureInterfaceMapping");	
				if(o != null){
					try{
						((edu.uci.isr.xarch.IXArchElement)o).setXArch(getXArch());
						if(de != null){
							de.cacheWrapper(el, ((edu.uci.isr.xarch.IXArchElement)o));
						}
						v.add((ISignatureInterfaceMapping)o);
					}
					catch(Exception e){
						SignatureInterfaceMappingImpl eltImpl = new SignatureInterfaceMappingImpl((Element)nl.item(i));
						eltImpl.setXArch(getXArch());
						if(de != null){
							de.cacheWrapper(el, ((edu.uci.isr.xarch.IXArchElement)eltImpl));
						}
						v.add(eltImpl);
					}
				}
				else{
					SignatureInterfaceMappingImpl eltImpl = new SignatureInterfaceMappingImpl((Element)nl.item(i));
					eltImpl.setXArch(getXArch());
					if(de != null){
						de.cacheWrapper(el, ((edu.uci.isr.xarch.IXArchElement)eltImpl));
					}
					v.add(eltImpl);
				}
			}
		}
		return v;
	}

	public boolean hasSignatureInterfaceMapping(ISignatureInterfaceMapping signatureInterfaceMappingToCheck){
		Collection c = getAllSignatureInterfaceMappings();
		
		for(Iterator en = c.iterator(); en.hasNext(); ){
			ISignatureInterfaceMapping elt = (ISignatureInterfaceMapping)en.next();
			if(elt.isEquivalent(signatureInterfaceMappingToCheck)){
				return true;
			}
		}
		return false;
	}
	
	public Collection hasSignatureInterfaceMappings(Collection signatureInterfaceMappingsToCheck){
		Vector v = new Vector();
		for(Iterator en = signatureInterfaceMappingsToCheck.iterator(); en.hasNext(); ){
			ISignatureInterfaceMapping elt = (ISignatureInterfaceMapping)en.next();
			v.addElement(new Boolean(hasSignatureInterfaceMapping(elt)));
		}
		return v;
	}
		
	public boolean hasAllSignatureInterfaceMappings(Collection signatureInterfaceMappingsToCheck){
		for(Iterator en = signatureInterfaceMappingsToCheck.iterator(); en.hasNext(); ){
			ISignatureInterfaceMapping elt = (ISignatureInterfaceMapping)en.next();
			if(!hasSignatureInterfaceMapping(elt)){
				return false;
			}
		}
		return true;
	}
	public ISignatureInterfaceMapping getSignatureInterfaceMapping(String id){
		NodeList nl = DOMUtils.getChildren(elt, TypesConstants.NS_URI, SIGNATURE_INTERFACE_MAPPING_ELT_NAME);
		for(int i = 0; i < nl.getLength(); i++){
			
			ISignatureInterfaceMapping el = new SignatureInterfaceMappingImpl((Element)nl.item(i));
			if(DOMUtils.objNullEq(id, el.getId())){
				Element domElt = (Element)nl.item(i);
				Object o = makeDerivedWrapper(domElt, "SignatureInterfaceMapping");
				if(o != null){
					try{
						((edu.uci.isr.xarch.IXArchElement)o).setXArch(getXArch());
						return (ISignatureInterfaceMapping)o;
					}
					catch(Exception e){}
				}
				el.setXArch(getXArch());
				return el;
			}
		}
		return null;
	}
	
	public Collection getSignatureInterfaceMappings(Collection ids){
		//If there is an ID that does not exist, it is simply ignored.
		//You can tell if this happened if ids.size() != returned collection.size().
		Vector v = new Vector();
		for(Iterator en = ids.iterator(); en.hasNext(); ){
			String elt = (String)en.next();
			ISignatureInterfaceMapping retElt = getSignatureInterfaceMapping(elt);
			if(retElt != null){
				v.addElement(retElt);
			}
		}
		return v;
	}	
	
	public boolean isEquivalent(ISubArchitecture c){
		return (getClass().equals(c.getClass())) &&
			hasArchStructure(c.getArchStructure()) &&
			hasAllSignatureInterfaceMappings(c.getAllSignatureInterfaceMappings()) &&
			c.hasAllSignatureInterfaceMappings(getAllSignatureInterfaceMappings()) ;
	}

}
