/*
 * Copyright (c) 2000-2005 Regents of the University of California.
 * All rights reserved.
 *
 * This software was developed at the University of California, Irvine.
 *
 * Redistribution and use in source and binary forms are permitted
 * provided that the above copyright notice and this paragraph are
 * duplicated in all such forms and that any documentation,
 * advertising materials, and other materials related to such
 * distribution and use acknowledge that the software was developed
 * by the University of California, Irvine.  The name of the
 * University may not be used to endorse or promote products derived
 * from this software without specific prior written permission.
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
 * WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */
package edu.uci.isr.xarch.instance;

import java.util.Collection;
import edu.uci.isr.xarch.XArchActionMetadata;
import edu.uci.isr.xarch.XArchTypeMetadata;
import edu.uci.isr.xarch.XArchPropertyMetadata;

/**
 * Interface for accessing objects of the
 * ComponentInstance <code>xsi:type</code> in the
 * instance namespace.
 * 
 * @author Automatically generated by xArch apigen
 */
public interface IComponentInstance extends edu.uci.isr.xarch.IXArchElement{

	public final static XArchTypeMetadata TYPE_METADATA = new XArchTypeMetadata(
		XArchTypeMetadata.XARCH_ELEMENT,
		"instance", "ComponentInstance", edu.uci.isr.xarch.IXArchElement.TYPE_METADATA,
		new XArchPropertyMetadata[]{
			XArchPropertyMetadata.createAttribute("id", "instance", "Identifier", null, null),
			XArchPropertyMetadata.createElement("description", "instance", "Description", 1, 1),
			XArchPropertyMetadata.createElement("interfaceInstance", "instance", "InterfaceInstance", 0, XArchPropertyMetadata.UNBOUNDED),
			XArchPropertyMetadata.createElement("subArchitecture", "instance", "SubArchitecture", 0, 1)},
		new XArchActionMetadata[]{});

	/**
	 * Set the id attribute on this ComponentInstance.
	 * @param id id
	 * @exception FixedValueException if the attribute has a fixed value
	 * and the value passed is not the fixed value.
	*/
	public void setId(String id);

	/**
	 * Remove the id attribute from this ComponentInstance.
	 */
	public void clearId();

	/**
	 * Get the id attribute from this ComponentInstance.
	 * if the attribute has a fixed value, this function will
	 * return that fixed value, even if it is not actually present
	 * in the XML document.
	 * @return id on this ComponentInstance
	 */
	public String getId();

	/**
	 * Determine if the id attribute on this ComponentInstance
	 * has the given value.
	 * @param id Attribute value to compare
	 * @return <code>true</code> if they match; <code>false</code>
	 * otherwise.
	 */
	public boolean hasId(String id);


	/**
	 * Set the description for this ComponentInstance.
	 * @param value new description
	 */
	public void setDescription(IDescription value);

	/**
	 * Clear the description from this ComponentInstance.
	 */
	public void clearDescription();

	/**
	 * Get the description from this ComponentInstance.
	 * @return description
	 */
	public IDescription getDescription();

	/**
	 * Determine if this ComponentInstance has the given description
	 * @param descriptionToCheck description to compare
	 * @return <code>true</code> if the descriptions are equivalent,
	 * <code>false</code> otherwise
	 */
	public boolean hasDescription(IDescription descriptionToCheck);

	/**
	 * Add a interfaceInstance to this ComponentInstance.
	 * @param newInterfaceInstance interfaceInstance to add.
	 */
	public void addInterfaceInstance(IInterfaceInstance newInterfaceInstance);

	/**
	 * Add a collection of interfaceInstances to this ComponentInstance.
	 * @param interfaceInstances interfaceInstances to add.
	 */
	public void addInterfaceInstances(Collection interfaceInstances);

	/**
	 * Remove all interfaceInstances from this ComponentInstance.
	 */
	public void clearInterfaceInstances();

	/**
	 * Remove the given interfaceInstance from this ComponentInstance.
	 * Matching is done by the <code>isEquivalent(...)</code> function.
	 * @param interfaceInstanceToRemove interfaceInstance to remove.
	 */
	public void removeInterfaceInstance(IInterfaceInstance interfaceInstanceToRemove);

	/**
	 * Remove all the given interfaceInstances from this ComponentInstance.
	 * Matching is done by the <code>isEquivalent(...)</code> function.
	 * @param interfaceInstances interfaceInstance to remove.
	 */
	public void removeInterfaceInstances(Collection interfaceInstances);

	/**
	 * Get all the interfaceInstances from this ComponentInstance.
	 * @return all interfaceInstances in this ComponentInstance.
	 */
	public Collection getAllInterfaceInstances();

	/**
	 * Determine if this ComponentInstance contains a given interfaceInstance.
	 * @return <code>true</code> if this ComponentInstance contains the given
	 * interfaceInstanceToCheck, <code>false</code> otherwise.
	 */
	public boolean hasInterfaceInstance(IInterfaceInstance interfaceInstanceToCheck);

	/**
	 * Determine if this ComponentInstance contains the given set of interfaceInstances.
	 * @param interfaceInstancesToCheck interfaceInstances to check for.
	 * @return Collection of <code>java.lang.Boolean</code>.  If the i<sup>th</sup>
	 * element in <code>interfaceInstances</code> was found, then the i<sup>th</sup>
	 * element of the collection will be set to <code>true</code>, otherwise it
	 * will be set to <code>false</code>.  Matching is done with the
	 * <code>isEquivalent(...)</code> method.
	 */
	public Collection hasInterfaceInstances(Collection interfaceInstancesToCheck);

	/**
	 * Determine if this ComponentInstance contains each element in the 
	 * given set of interfaceInstances.
	 * @param interfaceInstancesToCheck interfaceInstances to check for.
	 * @return <code>true</code> if every element in
	 * <code>interfaceInstances</code> is found in this ComponentInstance,
	 * <code>false</code> otherwise.
	 */
	public boolean hasAllInterfaceInstances(Collection interfaceInstancesToCheck);

	/**
	 * Gets the interfaceInstance from this ComponentInstance with the given
	 * id.
	 * @param id ID to look for.
	 * @return interfaceInstance with the given ID, or <code>null</code> if not found.
	 */
	public IInterfaceInstance getInterfaceInstance(String id);

	/**
	 * Gets the interfaceInstances from this ComponentInstance with the given
	 * ids.
	 * @param ids ID to look for.
	 * @return interfaceInstances with the given IDs.  If an element with a given
	 * ID was not found, that ID is ignored.
	 */
	public Collection getInterfaceInstances(Collection ids);


	/**
	 * Set the subArchitecture for this ComponentInstance.
	 * @param value new subArchitecture
	 */
	public void setSubArchitecture(ISubArchitecture value);

	/**
	 * Clear the subArchitecture from this ComponentInstance.
	 */
	public void clearSubArchitecture();

	/**
	 * Get the subArchitecture from this ComponentInstance.
	 * @return subArchitecture
	 */
	public ISubArchitecture getSubArchitecture();

	/**
	 * Determine if this ComponentInstance has the given subArchitecture
	 * @param subArchitectureToCheck subArchitecture to compare
	 * @return <code>true</code> if the subArchitectures are equivalent,
	 * <code>false</code> otherwise
	 */
	public boolean hasSubArchitecture(ISubArchitecture subArchitectureToCheck);
	/**
	 * Determine if another ComponentInstance has the same
	 * id as this one.
	 * @param ComponentInstanceToCheck ComponentInstance to compare with this
	 * one.
	 */
	public boolean isEqual(IComponentInstance ComponentInstanceToCheck);
	/**
	 * Determine if another ComponentInstance is equivalent to this one, ignoring
	 * ID's.
	 * @param ComponentInstanceToCheck ComponentInstance to compare to this one.
	 * @return <code>true</code> if all the child elements of this
	 * ComponentInstance are equivalent, <code>false</code> otherwise.
	 */
	public boolean isEquivalent(IComponentInstance ComponentInstanceToCheck);

}
