/*
 * Copyright (c) 2000-2005 Regents of the University of California.
 * All rights reserved.
 *
 * This software was developed at the University of California, Irvine.
 *
 * Redistribution and use in source and binary forms are permitted
 * provided that the above copyright notice and this paragraph are
 * duplicated in all such forms and that any documentation,
 * advertising materials, and other materials related to such
 * distribution and use acknowledge that the software was developed
 * by the University of California, Irvine.  The name of the
 * University may not be used to endorse or promote products derived
 * from this software without specific prior written permission.
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
 * WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */
package edu.uci.isr.xarch.instance;

import java.util.Collection;
import edu.uci.isr.xarch.XArchActionMetadata;
import edu.uci.isr.xarch.XArchTypeMetadata;
import edu.uci.isr.xarch.XArchPropertyMetadata;

/**
 * Interface for accessing objects of the
 * InterfaceInstance <code>xsi:type</code> in the
 * instance namespace.
 * 
 * @author Automatically generated by xArch apigen
 */
public interface IInterfaceInstance extends edu.uci.isr.xarch.IXArchElement{

	public final static XArchTypeMetadata TYPE_METADATA = new XArchTypeMetadata(
		XArchTypeMetadata.XARCH_ELEMENT,
		"instance", "InterfaceInstance", edu.uci.isr.xarch.IXArchElement.TYPE_METADATA,
		new XArchPropertyMetadata[]{
			XArchPropertyMetadata.createAttribute("id", "instance", "Identifier", null, null),
			XArchPropertyMetadata.createElement("description", "instance", "Description", 1, 1),
			XArchPropertyMetadata.createElement("direction", "instance", "Direction", 0, 1)},
		new XArchActionMetadata[]{});

	/**
	 * Set the id attribute on this InterfaceInstance.
	 * @param id id
	 * @exception FixedValueException if the attribute has a fixed value
	 * and the value passed is not the fixed value.
	*/
	public void setId(String id);

	/**
	 * Remove the id attribute from this InterfaceInstance.
	 */
	public void clearId();

	/**
	 * Get the id attribute from this InterfaceInstance.
	 * if the attribute has a fixed value, this function will
	 * return that fixed value, even if it is not actually present
	 * in the XML document.
	 * @return id on this InterfaceInstance
	 */
	public String getId();

	/**
	 * Determine if the id attribute on this InterfaceInstance
	 * has the given value.
	 * @param id Attribute value to compare
	 * @return <code>true</code> if they match; <code>false</code>
	 * otherwise.
	 */
	public boolean hasId(String id);


	/**
	 * Set the description for this InterfaceInstance.
	 * @param value new description
	 */
	public void setDescription(IDescription value);

	/**
	 * Clear the description from this InterfaceInstance.
	 */
	public void clearDescription();

	/**
	 * Get the description from this InterfaceInstance.
	 * @return description
	 */
	public IDescription getDescription();

	/**
	 * Determine if this InterfaceInstance has the given description
	 * @param descriptionToCheck description to compare
	 * @return <code>true</code> if the descriptions are equivalent,
	 * <code>false</code> otherwise
	 */
	public boolean hasDescription(IDescription descriptionToCheck);

	/**
	 * Set the direction for this InterfaceInstance.
	 * @param value new direction
	 */
	public void setDirection(IDirection value);

	/**
	 * Clear the direction from this InterfaceInstance.
	 */
	public void clearDirection();

	/**
	 * Get the direction from this InterfaceInstance.
	 * @return direction
	 */
	public IDirection getDirection();

	/**
	 * Determine if this InterfaceInstance has the given direction
	 * @param directionToCheck direction to compare
	 * @return <code>true</code> if the directions are equivalent,
	 * <code>false</code> otherwise
	 */
	public boolean hasDirection(IDirection directionToCheck);
	/**
	 * Determine if another InterfaceInstance has the same
	 * id as this one.
	 * @param InterfaceInstanceToCheck InterfaceInstance to compare with this
	 * one.
	 */
	public boolean isEqual(IInterfaceInstance InterfaceInstanceToCheck);
	/**
	 * Determine if another InterfaceInstance is equivalent to this one, ignoring
	 * ID's.
	 * @param InterfaceInstanceToCheck InterfaceInstance to compare to this one.
	 * @return <code>true</code> if all the child elements of this
	 * InterfaceInstance are equivalent, <code>false</code> otherwise.
	 */
	public boolean isEquivalent(IInterfaceInstance InterfaceInstanceToCheck);

}
